name: Static testing

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel prevous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  cache_dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18.12.1'
      - name: Install dependencies
        run: npm ci

  lint:
    needs: cache_dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18.12.1'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  tsc_check:
    needs: cache_dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '18.12.1'
      - name: Install dependencies
        run: npm ci
      - name: TypeScript checking
        run: npm run tsc:check
